branches:
  only:
    - master
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
addons:
  firefox: "65.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script: xvfb-run bundle exec rspec
