name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    steps:
      - uses: actions/checkout@v2

      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '65.0'

      - name: Set up geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
          mkdir geckodriver
          tar -xzf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -C geckodriver
          echo "$PWD/geckodriver" >> $GITHUB_PATH
        env:
          GECKODRIVER_VERSION: 0.21.0

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: xvfb-run bundle exec rspec
